// <auto-generated />
namespace DataBase.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Rename_NameClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_NameClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202008021452011_Rename_NameClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
